# coding: utf-8

"""
    Formula 1 Drivers API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_drivers_driver_id_delete(self) -> None:
        """Test case for api_drivers_driver_id_delete

        Delete a driver
        """
        pass

    def test_api_drivers_driver_id_get(self) -> None:
        """Test case for api_drivers_driver_id_get

        Get details of a specific driver
        """
        pass

    def test_api_drivers_driver_id_patch(self) -> None:
        """Test case for api_drivers_driver_id_patch

        Update driver details
        """
        pass

    def test_api_drivers_get(self) -> None:
        """Test case for api_drivers_get

        Get a list of all drivers
        """
        pass

    def test_api_drivers_post(self) -> None:
        """Test case for api_drivers_post

        Add a new driver
        """
        pass


if __name__ == '__main__':
    unittest.main()
