from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DriverUpdates(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, wins=None, poles=None):  # noqa: E501
        """DriverUpdates - a model defined in OpenAPI

        :param wins: The wins of this DriverUpdates.  # noqa: E501
        :type wins: int
        :param poles: The poles of this DriverUpdates.  # noqa: E501
        :type poles: int
        """
        self.openapi_types = {
            'wins': int,
            'poles': int
        }

        self.attribute_map = {
            'wins': 'wins',
            'poles': 'poles'
        }

        self._wins = wins
        self._poles = poles

    @classmethod
    def from_dict(cls, dikt) -> 'DriverUpdates':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DriverUpdates of this DriverUpdates.  # noqa: E501
        :rtype: DriverUpdates
        """
        return util.deserialize_model(dikt, cls)

    @property
    def wins(self) -> int:
        """Gets the wins of this DriverUpdates.


        :return: The wins of this DriverUpdates.
        :rtype: int
        """
        return self._wins

    @wins.setter
    def wins(self, wins: int):
        """Sets the wins of this DriverUpdates.


        :param wins: The wins of this DriverUpdates.
        :type wins: int
        """

        self._wins = wins

    @property
    def poles(self) -> int:
        """Gets the poles of this DriverUpdates.


        :return: The poles of this DriverUpdates.
        :rtype: int
        """
        return self._poles

    @poles.setter
    def poles(self, poles: int):
        """Sets the poles of this DriverUpdates.


        :param poles: The poles of this DriverUpdates.
        :type poles: int
        """

        self._poles = poles
